name: Generate terraform docs

on:
  pull_request:

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Render terraform docs and fail on diff
        uses: step-security/terraform-docs-action@43f977ff483b4dcf2d1c13fce93bfc30b1164bd9 # v1.4.4
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          fail-on-diff: "true"

      - name: Dump README
        if: failure()
        run: |
          cat README.md
