name: Generate terraform docs

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Render terraform docs and fail on diff
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          fail-on-diff: "true"
      - name: Dump README
        if: failure()
        run: |
          cat README.md
