name: Validate, Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-validate:
    name: "Terraform fmt and validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
      - name: Lint
        run: |
          terraform fmt -check
      - name: Validate
        run: |
          terraform init
          terraform validate
