name: Validate, Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-validate:
    name: "Terraform fmt and validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      - name: Lint
        run: |
          terraform fmt -check
      - name: Validate
        run: |
          terraform init
          terraform validate
