name: Validate, Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-validate:
    name: "Terraform fmt and validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800 # v3.1.0
      - name: Lint
        run: |
          terraform fmt -check
      - name: Validate
        run: |
          terraform init
          terraform validate
