name: Validate, Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-validate:
    name: "Terraform fmt and validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      - name: Lint
        run: |
          terraform fmt -check
      - name: Validate
        run: |
          terraform init
          terraform validate
